_target_: lsr.datasets.multi_psgs_pairs.MultiPSGsPairs
collection_path: "data/msmarco_doc/collection_psgs.tsv"
query_path: "data/msmarco_doc/msmarco-docdev-queries.tsv"
run_path: "outputs/qmlp_dmlm_distil_sentence_transformer_kl_l1_0.0001/msmarco_doc/run_doc.trec"
qrel_path: "data/msmarco_doc/msmarco-docdev-qrels.tsv" 
top_k: 100
num_psgs: 1