_target_: lsr.datasets.multi_psgs_pairs.MultiPSGsPairs
collection_path: "data/msmarco_doc/collection_psgs.tsv"
query_path: "data/msmarco_doc/msmarco-docdev-queries.tsv"
run_path: "run_files_top200/run_max_score_1.trec"
qrel_path: "data/msmarco_doc/msmarco-docdev-qrels.tsv" 
top_k: 100
num_psgs: 1